package co.gararetech.cinemas.view;

import co.gararetech.cinemas.controller.BookingTicketController;
import co.gararetech.cinemas.controller.DashboardController;
import co.gararetech.cinemas.model.BookingTicketModel;
import co.gararetech.cinemas.view.elements.RoundedPanel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

public class BookingTicketView extends javax.swing.JFrame {

    private BookingTicketController bookingTicketController;
    private BookingTicketModel bookingTicketModel;
    private ImageIcon appIcon;

    public BookingTicketView() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        Properties p = new Properties();
        p.put("windowTitleFont", "Ebrima PLAIN 15");
        p.put("logoString", "");
        p.put("windowDecoration", "off");
        AluminiumLookAndFeel.setCurrentTheme(p);
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        initComponents();

        appIcon = new ImageIcon(getClass().getResource("images/chair.png"));
        this.setIconImage(appIcon.getImage());

    }


    public BookingTicketController getBookingTicketController() {
        return bookingTicketController;
    }

    public void setBookingTicketController(BookingTicketController bookingTicketController) {
        this.bookingTicketController = bookingTicketController;
    }

    public BookingTicketModel getBookingTicketModel() {
        return bookingTicketModel;
    }

    public void setBookingTicketModel(BookingTicketModel bookingTicketModel) {
        this.bookingTicketModel = bookingTicketModel;
    }

    public JScrollPane getScrollTampilKursi() {
        return scrollTampilKursi;
    }

    public JPanel getPanelKursi() {
        return panelKursi;
    }

    public JPanel getPanelHarga() {
        return panelHarga;
    }

    public JPanel getPanelTampilKursi() {
        return panelTampilKursi;
    }

    public JTextField getTampilHarga() {
        return tampilHarga;
    }

    public JTextField getTampilTax() {
        return tampilTax;
    }

    public JButton getBtnBayar() {
        return btnBayar;
    }

    public JTextField getTampilHargaTiket() {
        return tampilHargaTiket;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelKursi = new RoundedPanel();
        jPanel1 = new RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel();
        panelHarga = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tampilTax = new javax.swing.JTextField();
        tampilTotalHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tampilHargaTiket = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tampilHarga = new javax.swing.JTextField();
        panelTampilKursi = new javax.swing.JPanel();
        scrollTampilKursi = new javax.swing.JScrollPane();
        scrollTampilKursi.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0));
        scrollTampilKursi.getVerticalScrollBar().setUnitIncrement(25);
        tampilKursi = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 640));
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUtama.setBackground(new java.awt.Color(66, 56, 47));
        panelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(29, 28, 28));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeaderMouseDragged(evt);
            }
        });
        panelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeaderMousePressed(evt);
            }
        });
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/gararetech/cinemas/view/images/logo-159.png"))); // NOI18N
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 18, -1, -1));

        panelUtama.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 90));

        panelKursi.setBackground(new java.awt.Color(25, 24, 28));
        panelKursi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LAYAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        panelKursi.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 650, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TERSEDIA");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 5, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 20, 20));

        jPanel5.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 5, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PILIHAN ANDA");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 5, -1, 20));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 5, 20, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TELAH DIPESAN");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 5, -1, -1));

        panelKursi.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 10, 560, 35));

        panelUtama.add(panelKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 690, 510));

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHarga.setBackground(new java.awt.Color(34, 34, 34));
        panelHarga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL HARGA");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(81, 81, 81)));
        panelHarga.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(116, 116, 116));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tax :");
        panelHarga.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        tampilTax.setBackground(new java.awt.Color(34, 34, 34));
        tampilTax.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tampilTax.setForeground(new java.awt.Color(255, 255, 255));
        tampilTax.setBorder(null);
        tampilTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilTaxActionPerformed(evt);
            }
        });
        panelHarga.add(tampilTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 20));

        tampilTotalHarga.setBackground(new java.awt.Color(34, 34, 34));
        tampilTotalHarga.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tampilTotalHarga.setForeground(new java.awt.Color(255, 255, 255));
        tampilTotalHarga.setText("Rp 0.0");
        tampilTotalHarga.setBorder(null);
        tampilTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilTotalHargaActionPerformed(evt);
            }
        });
        panelHarga.add(tampilTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(116, 116, 116));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total Bayar :");
        panelHarga.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(116, 116, 116));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Harga Tiket :");
        panelHarga.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        tampilHargaTiket.setBackground(new java.awt.Color(34, 34, 34));
        tampilHargaTiket.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tampilHargaTiket.setForeground(new java.awt.Color(255, 255, 255));
        tampilHargaTiket.setText("Rp 0.0");
        tampilHargaTiket.setBorder(null);
        panelHarga.add(tampilHargaTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TEMPAT DUDUK");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(81, 81, 81)));
        panelHarga.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(116, 116, 116));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Total Harga :");
        panelHarga.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        tampilHarga.setBackground(new java.awt.Color(34, 34, 34));
        tampilHarga.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tampilHarga.setForeground(new java.awt.Color(255, 255, 255));
        tampilHarga.setText("Rp 0.0");
        tampilHarga.setBorder(null);
        tampilHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilHargaActionPerformed(evt);
            }
        });
        panelHarga.add(tampilHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, 20));

        jPanel2.add(panelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 220));

        panelTampilKursi.setBackground(new java.awt.Color(34, 34, 34));
        panelTampilKursi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollTampilKursi.setBorder(null);
        scrollTampilKursi.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollTampilKursi.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollTampilKursi.setAutoscrolls(true);

        tampilKursi.setBackground(new java.awt.Color(34, 34, 34));
        tampilKursi.setLayout(new java.awt.CardLayout(10, 10));
        scrollTampilKursi.setViewportView(tampilKursi);

        panelTampilKursi.add(scrollTampilKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 140));

        btnKembali.setBackground(Color.decode("#A27B5C"));
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        panelTampilKursi.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 35));

        btnBayar.setBackground(Color.decode("#2E5B0B"));
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("BAYAR");
        btnBayar.setEnabled(false);
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        panelTampilKursi.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 35));

        jPanel2.add(panelTampilKursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 260));

        panelUtama.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 270, 510));

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampilTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilTaxActionPerformed

    private void tampilTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilTotalHargaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        bookingTicketController.back(this);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        bookingTicketController.bookNow(this);
    }//GEN-LAST:event_btnBayarActionPerformed

    private void tampilHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilHargaActionPerformed

    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
        // TODO add your handling code here:
        bookingTicketController.handleMouseDragged(evt, this);
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void panelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMousePressed
        // TODO add your handling code here:
        bookingTicketController.handleMousePressed(evt, this);
    }//GEN-LAST:event_panelHeaderMousePressed

    public JTextField getTampilTotalHarga() {
        return tampilTotalHarga;
    }

    public void setTampilTotalHarga(JTextField tampilTotalHarga) {
        this.tampilTotalHarga = tampilTotalHarga;
    }

    public JPanel getTampilKursi() {
        return tampilKursi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingTicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BookingTicketView().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BookingTicketView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(BookingTicketView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(BookingTicketView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(BookingTicketView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panelHarga;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelKursi;
    private javax.swing.JPanel panelTampilKursi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JScrollPane scrollTampilKursi;
    private javax.swing.JTextField tampilHarga;
    private javax.swing.JTextField tampilHargaTiket;
    private javax.swing.JPanel tampilKursi;
    private javax.swing.JTextField tampilTax;
    private javax.swing.JTextField tampilTotalHarga;
    // End of variables declaration//GEN-END:variables
}
