package co.gararetech.cinemas.view;

import co.gararetech.cinemas.controller.CinemaListController;
import co.gararetech.cinemas.controller.DashboardController;
import co.gararetech.cinemas.controller.NowPlayingController;
import co.gararetech.cinemas.controller.OrderHistoryContoller;
import co.gararetech.cinemas.controller.UpcomingController;
import co.gararetech.cinemas.model.DashboardModel;
import co.gararetech.cinemas.utils.GoogleCloudStorage;
import co.gararetech.cinemas.view.elements.RoundJButton;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.Color;
import java.io.IOException;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class DashboardView extends javax.swing.JFrame {

    private AboutUsView aboutusview;
    private NowPlayingController nowPlayingController;
    private UpcomingController upcomingController;
    private OrderHistoryContoller orderHistoryController;
    private CinemaListController cinemaListController;
    private DashboardController dashboardController;
    private GoogleCloudStorage googleCloudStorage;
    private DashboardModel dashboardModel;
    private ImageIcon appIcon;
    private JPanel loadingPanel;
    private JDialog loadingUser;

    public DashboardView() throws ClassNotFoundException, InstantiationException, UnsupportedLookAndFeelException, IllegalAccessException, URISyntaxException, IOException {
        Properties p = new Properties();
        p.put("windowTitleFont", "Ebrima PLAIN 15");
        p.put("logoString", "");
        p.put("windowDecoration", "off");
        AluminiumLookAndFeel.setCurrentTheme(p);
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        dashboardController = new DashboardController();
        dashboardModel = new DashboardModel();
        nowPlayingController = new NowPlayingController();
        upcomingController = new UpcomingController();
        cinemaListController = new CinemaListController();
        orderHistoryController = new OrderHistoryContoller();
        googleCloudStorage = new GoogleCloudStorage();
        aboutusview = new AboutUsView();
        
        initComponents();

        dashboardController.setModel(dashboardModel);
        nowPlayingController.setModel(dashboardModel);
        upcomingController.setModel(dashboardModel);
        cinemaListController.setModel(dashboardModel);
        orderHistoryController.setModel(dashboardModel);

        appIcon = new ImageIcon(getClass().getResource("images/chair.png"));
        this.setIconImage(appIcon.getImage());

        dashboardController.openFirstTab(this, nowPlayingController);
    }

    public NowPlayingController getNowPlayingController() {
        return nowPlayingController;
    }

    public UpcomingController getUpcomingController() {
        return upcomingController;
    }

    public OrderHistoryContoller getOrderHistoryController() {
        return orderHistoryController;
    }

    public CinemaListController getCinemaListController() {
        return cinemaListController;
    }

    public JButton getBtnProfile() {
        return btnProfile;
    }

    public void setBtnProfile(JButton btnProfile) {
        this.btnProfile = btnProfile;
    }

    public JPanel getLoadingPanel() {
        return loadingPanel;
    }

    public void setLoadingPanel(JPanel loadingPanel) {
        this.loadingPanel = loadingPanel;
    }

    public JButton getBtnCinema() {
        return btnCinema;
    }

    public JButton getBtnNowPlaying() {
        return btnNowPlaying;
    }

    public JButton getBtnOrderHistory() {
        return btnOrderHistory;
    }

    public JButton getBtnUpcoming() {
        return btnUpcoming;
    }

    public JPanel getContent() {
        return content;
    }

    public DashboardModel getModel() {
        return dashboardModel;
    }

    public DashboardController getDashboardController() {
        return dashboardController;
    }

    public DashboardModel getDashboardModel() {
        return dashboardModel;
    }

    public JDialog getLoadingUser() {
        return loadingUser;
    }

    public void setLoadingUser(JDialog loadingUser) {
        this.loadingUser = loadingUser;
    }

    public JPopupMenu getPopupProfile() {
        return popupProfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupProfile = new javax.swing.JPopupMenu();
        editProfile = new javax.swing.JMenuItem();
        bugReport = new javax.swing.JMenuItem();
        aboutUs = new javax.swing.JMenuItem();
        line = new javax.swing.JPopupMenu.Separator();
        Logout = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNowPlaying = new javax.swing.JButton();
        btnUpcoming = new javax.swing.JButton();
        btnCinema = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        contentPane = new javax.swing.JScrollPane();
        contentPane.getVerticalScrollBar().setUnitIncrement(25);
        content = new javax.swing.JPanel();

        editProfile.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        editProfile.setText("Edit Profile");
        editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileActionPerformed(evt);
            }
        });
        popupProfile.add(editProfile);

        bugReport.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        bugReport.setText("Bug Report");
        bugReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugReportActionPerformed(evt);
            }
        });
        popupProfile.add(bugReport);

        aboutUs.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        aboutUs.setText("About Us");
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsPerformed(evt);
            }
        });
        popupProfile.add(aboutUs);
        popupProfile.add(line);

        Logout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        popupProfile.add(Logout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinemas Booking App");
        setMaximumSize(new java.awt.Dimension(1212, 640));
        setMinimumSize(new java.awt.Dimension(1212, 640));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1212, 640));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(Color.decode("#1D1C1C"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 85));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/gararetech/cinemas/view/images/logo-159.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, 57));

        btnNowPlaying.setBackground(Color.decode("#3D3C3A"));
        btnNowPlaying.setForeground(new java.awt.Color(255, 255, 255));
        btnNowPlaying.setText("Sedang Tayang");
        btnNowPlaying.setToolTipText("Sedang Tayang");
        btnNowPlaying.setFocusPainted(false);
        btnNowPlaying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNowPlayingActionPerformed(evt);
            }
        });
        jPanel1.add(btnNowPlaying, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 27, 153, 32));

        btnUpcoming.setBackground(Color.decode("#D9D9D9"));
        btnUpcoming.setForeground(new java.awt.Color(0, 0, 0));
        btnUpcoming.setText("Segera Tayang");
        btnUpcoming.setToolTipText("Segera Tayang");
        btnUpcoming.setFocusPainted(false);
        btnUpcoming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpcomingActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpcoming, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 27, 153, 32));

        btnCinema.setBackground(Color.decode("#D9D9D9"));
        btnCinema.setText("Bioskop");
        btnCinema.setToolTipText("Bioskop");
        btnCinema.setFocusPainted(false);
        btnCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinemaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCinema, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 27, 153, 32));

        btnOrderHistory.setBackground(Color.decode("#D9D9D9"));
        btnOrderHistory.setText("Riwayat Pesanan");
        btnOrderHistory.setToolTipText("Riwayat Pesanan");
        btnOrderHistory.setFocusPainted(false);
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrderHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 27, 153, 32));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/gararetech/cinemas/view/images/minimizeButton.png"))); // NOI18N
        minimize.setToolTipText("Minimize");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.setIconTextGap(0);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 6, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/gararetech/cinemas/view/images/exitButton.png"))); // NOI18N
        exit.setToolTipText("Close");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setIconTextGap(0);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 6, -1, -1));

        btnProfile.setBackground(Color.decode("#D9D9D9"));
        btnProfile.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/gararetech/cinemas/view/images/ProfileIconBlack.png"))); // NOI18N
        btnProfile.setToolTipText("Profile");
        btnProfile.setBorderPainted(false);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setFocusable(false);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        jPanel1.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 12, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1212, 90));

        contentPane.setBackground(new java.awt.Color(102, 102, 102));
        contentPane.setBorder(null);
        contentPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        contentPane.setPreferredSize(new java.awt.Dimension(1050, 600));

        content.setBackground(Color.decode("#42382F"));
        content.setLayout(new java.awt.GridLayout(1, 0));
        contentPane.setViewportView(content);

        getContentPane().add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1230, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        dashboardController.handleMouseDragged(evt, this);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        dashboardController.hidePopupProfile(this);
        dashboardController.handleMousePressed(evt, this);
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnUpcomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpcomingActionPerformed
        // TODO add your handling code here:
        dashboardController.openTab(upcomingController, this);
    }//GEN-LAST:event_btnUpcomingActionPerformed

    private void btnNowPlayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNowPlayingActionPerformed
        // TODO add your handling code here:
        dashboardController.openTab(nowPlayingController, this);
    }//GEN-LAST:event_btnNowPlayingActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        dashboardController.exitButton(this);
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        dashboardController.minimizeButton(this);
    }//GEN-LAST:event_minimizeMouseClicked

    private void btnCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinemaActionPerformed
        // TODO add your handling code here:
        dashboardController.openTab(cinemaListController, this);
    }//GEN-LAST:event_btnCinemaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        // TODO add your handling code here:
        dashboardController.openTab(orderHistoryController, this);
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    private void editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileActionPerformed
        // TODO add your handling code here:
        dashboardController.openProfileTab(this);
    }//GEN-LAST:event_editProfileActionPerformed

    private void aboutUsPerformed(java.awt.event.ActionEvent evt) {
        aboutusview.setVisible(true);
    }

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        try {
            // TODO add your handling code here:
            dashboardController.logout(this, new LoginView());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(DashboardView.this, "Kesalahan system " + ex.getMessage());
            Logger.getLogger(DashboardView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void bugReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugReportActionPerformed
        // TODO add your handling code here:
        dashboardController.viewBugReport(this);
    }//GEN-LAST:event_bugReportActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        dashboardController.showPopupProfile(this);
    }//GEN-LAST:event_btnProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DashboardView().setVisible(false);

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Kesalahan system " + ex.getMessage());
                    Logger.getLogger(DashboardView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem aboutUs;
    private javax.swing.JButton btnCinema;
    private javax.swing.JButton btnNowPlaying;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnUpcoming;
    private javax.swing.JMenuItem bugReport;
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane contentPane;
    private javax.swing.JMenuItem editProfile;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator line;
    private javax.swing.JLabel minimize;
    private javax.swing.JPopupMenu popupProfile;
    // End of variables declaration//GEN-END:variables
}
