/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.gararetech.cinemas.view;

import co.gararetech.cinemas.controller.DashboardController;
import co.gararetech.cinemas.controller.ProfileController;
import co.gararetech.cinemas.model.ProfileModel;
import co.gararetech.cinemas.utils.GoogleCloudStorage;
import co.gararetech.cinemas.view.elements.RoundJPasswordField;
import co.gararetech.cinemas.view.elements.RoundJTextField;
import co.gararetech.cinemas.view.elements.RoundJCBox;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.Color;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Acer
 */
public class ProfileView extends javax.swing.JFrame {

    /**
     * Creates new form ProfilView
     */
    private GoogleCloudStorage googleCloudStorage;
    private ProfileController profileController;
    private DashboardController dashboardController;
    private ProfileModel profileModel;
    private DashboardView dashboardView;
    private ImageIcon appIcon;
    private int mouseX;
    private int mouseY;

    public ProfileView() throws ClassNotFoundException, IllegalAccessException, UnsupportedLookAndFeelException, InstantiationException, URISyntaxException, IOException {
        Properties p = new Properties();
        p.put("windowTitleFont", "Ebrima PLAIN 15");
        p.put("logoString", "");
        p.put("windowDecoration", "off");
        AluminiumLookAndFeel.setCurrentTheme(p);
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        profileController = new ProfileController();
        profileModel = new ProfileModel();
        googleCloudStorage = new GoogleCloudStorage();
        dashboardController = new DashboardController();
        initComponents();
        profileController.setModel(profileModel);
        appIcon = new ImageIcon(getClass().getResource("images/chair.png"));
        this.setIconImage(appIcon.getImage());
        new SwingWorker<Void, Void>() {
            @Override
            public Void doInBackground() {
                try {
                    profileController.pictureload(ProfileView.this);
                } catch (IOException ex) {
                    Logger.getLogger(ProfileView.class.getName()).log(Level.SEVERE, null, ex);
                }
                return null;
            }
        }.execute();
    }

    
        
    

    public void setDashboardView(DashboardView dashboardView) {
        this.dashboardView = dashboardView;
    }

    public DashboardView getDashboardView() {
        return dashboardView;
    }

    public ProfileController getProfileController() {
        return profileController;
    }

    public ProfileModel getProfileModel() {
        return profileModel;
    }

    public int getMouseX() {
        return mouseX;
    }

    public void setMouseX(int mouseX) {
        this.mouseX = mouseX;
    }

    public int getMouseY() {
        return mouseY;
    }

    public void setMouseY(int mouseY) {
        this.mouseY = mouseY;
    }

    public JCheckBox getIsChangePassword() {
        return isChangePassword;
    }

    public JComboBox getjCity() {
        return jCity;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JPasswordField getTxtNewPassword() {
        return txtNewPassword;
    }

    public JPasswordField getTxtOldPassword() {
        return txtOldPassword;
    }

    public JLabel getProfilePicture() {
        return profilePicture;
    }

    public JButton getBtnProfileSave() {
        return btnProfileSave;
    }

    public GoogleCloudStorage getGoogleCloudStorage() {
        return googleCloudStorage;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnProfileSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jCity = new javax.swing.JComboBox();
        isChangePassword = new javax.swing.JCheckBox();
        profilePicture = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinemas Booking App");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(849, 785));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 12, 12)));
        jPanel2.setPreferredSize(new java.awt.Dimension(731, 502));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMAIL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 120, 57, -1));

        txtEmail.setBackground(new java.awt.Color(0, 0, 0));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setToolTipText("Email");
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtEmail.setCaretColor(new java.awt.Color(54, 12, 12));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 250, 38));

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD LAMA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 375, -1, -1));

        btnBack.setBackground(new java.awt.Color(217, 217, 217));
        btnBack.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("KEMBALI");
        btnBack.setToolTipText("Kembali");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 515, 250, 36));

        btnProfileSave.setBackground(new java.awt.Color(217, 217, 217));
        btnProfileSave.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnProfileSave.setForeground(new java.awt.Color(0, 0, 0));
        btnProfileSave.setText("SIMPAN");
        btnProfileSave.setToolTipText("Simpan");
        btnProfileSave.setBorder(null);
        btnProfileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnProfileSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 466, 250, 36));

        jLabel4.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PASSWORD BARU");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 300, -1, -1));

        txtOldPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtOldPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOldPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtOldPassword.setToolTipText("Password Lama");
        txtOldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtOldPassword.setCaretColor(new java.awt.Color(54, 12, 12));
        txtOldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 395, 250, 38));

        txtNewPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtNewPassword.setToolTipText("Password Baru");
        txtNewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtNewPassword.setCaretColor(new java.awt.Color(54, 12, 12));
        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 320, 250, 36));

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("KOTA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 190, -1, -1));

        jCity.setBackground(new java.awt.Color(0, 0, 0));
        jCity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCity.setForeground(new java.awt.Color(255, 255, 255));
        jCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bandung", "Jakarta" }));
        jCity.setToolTipText("Kota");
        jCity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel2.add(jCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 250, 38));

        isChangePassword.setBackground(new java.awt.Color(0, 0, 0));
        isChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        isChangePassword.setText("Ubah Password");
        isChangePassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                isChangePasswordStateChanged(evt);
            }
        });
        isChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isChangePasswordActionPerformed(evt);
            }
        });
        jPanel2.add(isChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 270, 132, -1));

        profilePicture.setBackground(new java.awt.Color(255, 255, 255));
        profilePicture.setForeground(new java.awt.Color(255, 255, 255));
        profilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/gararetech/cinemas/view/images/ProfileIconBlack.png"))); // NOI18N
        profilePicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePictureMouseClicked(evt);
            }
        });
        jPanel2.add(profilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 7, 180, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2022");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 590, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gararetech Co.");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 570, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 470, 610));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROFILE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 80, 180, 65));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/gararetech/cinemas/view/images/logoGararetechLogin.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        profileController.back(this, this.getDashboardView());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProfileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileSaveActionPerformed
        profileController.loading(this.getBtnProfileSave(), true);
        new Thread() {
            public void run() {
                try {
                    profileController.updateUser(ProfileView.this);
                    profileController.loading(ProfileView.this.getBtnProfileSave(), false);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }.start();
    }//GEN-LAST:event_btnProfileSaveActionPerformed

    private void txtOldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldPasswordActionPerformed

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - this.getMouseX(), y - this.getMouseY());
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        this.setMouseX(evt.getX());
        this.setMouseY(evt.getY());
    }//GEN-LAST:event_jPanel1MousePressed

    private void isChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isChangePasswordActionPerformed

    private void isChangePasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_isChangePasswordStateChanged
        // TODO add your handling code here:
        profileController.selectedChangePassword(this, evt);
    }//GEN-LAST:event_isChangePasswordStateChanged

    private void profilePictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictureMouseClicked
        try {
            profileController.chooseImage(this, this.getGoogleCloudStorage());
        } catch (IOException ex) {
            Logger.getLogger(ProfileView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_profilePictureMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProfileView().setVisible(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Kesalahan system " + ex.getMessage());
                    Logger

.getLogger(ProfileView.class  

.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProfileSave;
    private javax.swing.JCheckBox isChangePassword;
    private javax.swing.JComboBox jCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
